---
dns_config:
  - host: nodeset.vv
#    this should eventually be a load balancer
    ip: 10.0.0.60
  - host: magicbox.vv
    ip: 10.0.0.46
  - host: node-2.vv
    ip: 10.0.0.60
# ingress:
  - host: vvv.run
    ip: 10.0.0.60